mongodb-rpibroker:
  image: mongo
  ports: 
    - "3502:27017"
  volumes:
    - ./data:/data/db
  command: mongod --smallfiles --logpath=/dev/null # -- quiet
  restart: always
    
connextcms-rpibroker:
  build: .
  dockerfile: Dockerfile
  links:
    - mongodb-rpibroker
  ports:
    - "3002:3000"
    - "8080:8080"
  volumes:
    - ./theme:/home/connextcms/theme
    - ./plugins:/home/connextcms/plugins
    - ./public:/home/connextcms/public
  restart: always
    
